// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: v1alpha1/certificaterequest.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertificateRequest is a single certificate signing request and private key
// from a client. A request _must_ include at least a PEM encoded X.509
// certificate signing request, but should _not_ be signed by a client's
// private key . A client may optionally request other certificate attributes
// that cannot be encoded inside a certificate signing request. These
// additional attributes may or may not be honored based on the server's
// configuration and authorization policy.
// Requests may be denied by the server following a authorization review.
type CertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// subject is an optional field used to specify desired subject distinguished name for the issued certificate.
	Subject *Subject `protobuf:"bytes,1,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	// subject is an optional field used to specify desired subject alternate names for the issued certificate.
	AltNames *AltNames `protobuf:"bytes,2,opt,name=alt_names,json=altNames,proto3,oneof" json:"alt_names,omitempty"`
	// key_type is an optional field used to specify parameters for the public and private keys.
	// The public key will be used to create the CSR which will be signed.
	// The private key will be returned to the client together with the issued certificate.
	KeyType *KeyType `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=certificates.v1alpha1.KeyType,oneof" json:"key_type,omitempty"`
	// validity_period is an optional field containing ISO8601 formatted duration the client wishes
	// the resulting X.509 certificate is signed for.
	// The specified Policy has same attribute, so the shorter duration will be used indeed.
	ValidityPeriod *string `protobuf:"bytes,4,opt,name=validity_period,json=validityPeriod,proto3,oneof" json:"validity_period,omitempty"`
	// policy_name contains the name of the Policy which the client wishes to request against.
	PolicyName string `protobuf:"bytes,5,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_certificaterequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_certificaterequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_certificaterequest_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CertificateRequest) GetAltNames() *AltNames {
	if x != nil {
		return x.AltNames
	}
	return nil
}

func (x *CertificateRequest) GetKeyType() KeyType {
	if x != nil && x.KeyType != nil {
		return *x.KeyType
	}
	return KeyType_RSA_2048
}

func (x *CertificateRequest) GetValidityPeriod() string {
	if x != nil && x.ValidityPeriod != nil {
		return *x.ValidityPeriod
	}
	return ""
}

func (x *CertificateRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

// CertificateRequestResponse is the server's response to a single certificate
// request from a client. The message contains a single PEM encoded X.509
// certificate chain, including the client's requested leaf certificate. The
// server will never return the root Certificate Authority (CA). The server may
// respond with a single certificate if the root CA is the issuer.
// The server will also respond with the client's PEM encoded private key,
// which will be paired with the returned signed leaf certificate.
// The leaf certificate is always the first certificate in the chain.
// The chain will always be in order of increasing issuer authority.
type CertificateRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// certificate_chain is the PEM encoded X.509 certificate chain returned in
	// response to a certificate signing request.
	// certificate_chain will never contain the root CA.
	// The signed client's leaf certificate will always be first in the chain.
	// The chain will always be in order of increasing issuer authority.
	CertificateChain []byte `protobuf:"bytes,1,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	// private_key is the PEM encoded private key which is paired with the
	// client's leaf certificate at the head of the certificate_chain.
	PrivateKey []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *CertificateRequestResponse) Reset() {
	*x = CertificateRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_certificaterequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequestResponse) ProtoMessage() {}

func (x *CertificateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_certificaterequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequestResponse.ProtoReflect.Descriptor instead.
func (*CertificateRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_certificaterequest_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateRequestResponse) GetCertificateChain() []byte {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *CertificateRequestResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

var File_v1alpha1_certificaterequest_proto protoreflect.FileDescriptor

var file_v1alpha1_certificaterequest_proto_rawDesc = []byte{
	0x0a, 0x21, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x16, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x6b, 0x65, 0x79, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x16, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe0, 0x02, 0x0a, 0x12, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x88, 0x01, 0x01, 0x12, 0x41, 0x0a, 0x09, 0x61, 0x6c, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x41, 0x6c, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x48, 0x01, 0x52, 0x08, 0x61,
	0x6c, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x3e, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x02, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x6c, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x12, 0x0a, 0x10, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x22, 0x6a, 0x0a, 0x1a, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x42, 0x72, 0x5a, 0x70, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76,
	0x65, 0x6e, 0x61, 0x66, 0x69, 0x2f, 0x76, 0x61, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x74, 0x6c, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x65, 0x63, 0x74, 0x2f, 0x64, 0x6d, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x66, 0x69, 0x72, 0x65,
	0x66, 0x6c, 0x79, 0x2d, 0x63, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha1_certificaterequest_proto_rawDescOnce sync.Once
	file_v1alpha1_certificaterequest_proto_rawDescData = file_v1alpha1_certificaterequest_proto_rawDesc
)

func file_v1alpha1_certificaterequest_proto_rawDescGZIP() []byte {
	file_v1alpha1_certificaterequest_proto_rawDescOnce.Do(func() {
		file_v1alpha1_certificaterequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha1_certificaterequest_proto_rawDescData)
	})
	return file_v1alpha1_certificaterequest_proto_rawDescData
}

var file_v1alpha1_certificaterequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1alpha1_certificaterequest_proto_goTypes = []interface{}{
	(*CertificateRequest)(nil),         // 0: certificates.v1alpha1.CertificateRequest
	(*CertificateRequestResponse)(nil), // 1: certificates.v1alpha1.CertificateRequestResponse
	(*Subject)(nil),                    // 2: certificates.v1alpha1.Subject
	(*AltNames)(nil),                   // 3: certificates.v1alpha1.AltNames
	(KeyType)(0),                       // 4: certificates.v1alpha1.KeyType
}
var file_v1alpha1_certificaterequest_proto_depIdxs = []int32{
	2, // 0: certificates.v1alpha1.CertificateRequest.subject:type_name -> certificates.v1alpha1.Subject
	3, // 1: certificates.v1alpha1.CertificateRequest.alt_names:type_name -> certificates.v1alpha1.AltNames
	4, // 2: certificates.v1alpha1.CertificateRequest.key_type:type_name -> certificates.v1alpha1.KeyType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1alpha1_certificaterequest_proto_init() }
func file_v1alpha1_certificaterequest_proto_init() {
	if File_v1alpha1_certificaterequest_proto != nil {
		return
	}
	file_v1alpha1_keytype_proto_init()
	file_v1alpha1_subject_proto_init()
	file_v1alpha1_usages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1alpha1_certificaterequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_certificaterequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1alpha1_certificaterequest_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha1_certificaterequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_certificaterequest_proto_goTypes,
		DependencyIndexes: file_v1alpha1_certificaterequest_proto_depIdxs,
		MessageInfos:      file_v1alpha1_certificaterequest_proto_msgTypes,
	}.Build()
	File_v1alpha1_certificaterequest_proto = out.File
	file_v1alpha1_certificaterequest_proto_rawDesc = nil
	file_v1alpha1_certificaterequest_proto_goTypes = nil
	file_v1alpha1_certificaterequest_proto_depIdxs = nil
}
