// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: v1alpha1/keytype.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyType defines the parameters for the public and private keys.
// It encodes the key algorithm(e.g. RSA algorithm) and some additional clarification(e.g. 2048 key size)
type KeyType int32

const (
	// RSA_2048 is the Rivest–Shamir–Adleman public key algorithm with key size of 2048
	KeyType_RSA_2048 KeyType = 0
	// RSA_3072 is the Rivest–Shamir–Adleman public key algorithm with key size of 3072
	KeyType_RSA_3072 KeyType = 1
	// RSA_4096 is the Rivest–Shamir–Adleman public key algorithm with key size of 4096
	KeyType_RSA_4096 KeyType = 2
	// EC_P256 is the Elliptic Curve Digital Signature Algorithm, curve type P256
	// https://en.wikipedia.org/wiki/Elliptic-curve_cryptography
	KeyType_EC_P256 KeyType = 3
	// EC_P384 is the Elliptic Curve Digital Signature Algorithm, curve type P384
	// https://en.wikipedia.org/wiki/Elliptic-curve_cryptography
	KeyType_EC_P384 KeyType = 4
	// EC_P521 is the Elliptic Curve Digital Signature Algorithm, curve type P521
	// https://en.wikipedia.org/wiki/Elliptic-curve_cryptography
	KeyType_EC_P521 KeyType = 5
	// EC_ED25519 is a EdDSA using Curve25519
	// https://en.wikipedia.org/wiki/EdDSA#Ed25519
	KeyType_EC_ED25519 KeyType = 6
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "RSA_2048",
		1: "RSA_3072",
		2: "RSA_4096",
		3: "EC_P256",
		4: "EC_P384",
		5: "EC_P521",
		6: "EC_ED25519",
	}
	KeyType_value = map[string]int32{
		"RSA_2048":   0,
		"RSA_3072":   1,
		"RSA_4096":   2,
		"EC_P256":    3,
		"EC_P384":    4,
		"EC_P521":    5,
		"EC_ED25519": 6,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_keytype_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_v1alpha1_keytype_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_keytype_proto_rawDescGZIP(), []int{0}
}

var File_v1alpha1_keytype_proto protoreflect.FileDescriptor

var file_v1alpha1_keytype_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6b, 0x65, 0x79, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2a,
	0x6a, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x53,
	0x41, 0x5f, 0x32, 0x30, 0x34, 0x38, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x53, 0x41, 0x5f,
	0x33, 0x30, 0x37, 0x32, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x53, 0x41, 0x5f, 0x34, 0x30,
	0x39, 0x36, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x43, 0x5f, 0x50, 0x32, 0x35, 0x36, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x43, 0x5f, 0x50, 0x33, 0x38, 0x34, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x45, 0x43, 0x5f, 0x50, 0x35, 0x32, 0x31, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x45,
	0x43, 0x5f, 0x45, 0x44, 0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x06, 0x42, 0x72, 0x5a, 0x70, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x65, 0x6e, 0x61, 0x66, 0x69,
	0x2f, 0x76, 0x61, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x74, 0x6c, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x2f, 0x64,
	0x6d, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x66, 0x69, 0x72, 0x65, 0x66, 0x6c, 0x79, 0x2d, 0x63,
	0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha1_keytype_proto_rawDescOnce sync.Once
	file_v1alpha1_keytype_proto_rawDescData = file_v1alpha1_keytype_proto_rawDesc
)

func file_v1alpha1_keytype_proto_rawDescGZIP() []byte {
	file_v1alpha1_keytype_proto_rawDescOnce.Do(func() {
		file_v1alpha1_keytype_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha1_keytype_proto_rawDescData)
	})
	return file_v1alpha1_keytype_proto_rawDescData
}

var file_v1alpha1_keytype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1alpha1_keytype_proto_goTypes = []interface{}{
	(KeyType)(0), // 0: certificates.v1alpha1.KeyType
}
var file_v1alpha1_keytype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1alpha1_keytype_proto_init() }
func file_v1alpha1_keytype_proto_init() {
	if File_v1alpha1_keytype_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha1_keytype_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_keytype_proto_goTypes,
		DependencyIndexes: file_v1alpha1_keytype_proto_depIdxs,
		EnumInfos:         file_v1alpha1_keytype_proto_enumTypes,
	}.Build()
	File_v1alpha1_keytype_proto = out.File
	file_v1alpha1_keytype_proto_rawDesc = nil
	file_v1alpha1_keytype_proto_goTypes = nil
	file_v1alpha1_keytype_proto_depIdxs = nil
}
